import pandas as pd
import numpy as np

def create_temporal_features(df):
    """
    Extracts temporal calendar features from DatetimeIndex.
    """
    df_feat = df.copy()
    if not isinstance(df_feat.index, pd.DatetimeIndex):
        raise ValueError("Dataframe must have a DatetimeIndex to generate temporal features.")
        
    df_feat['hour'] = df_feat.index.hour
    df_feat['day_of_week'] = df_feat.index.dayofweek
    df_feat['month'] = df_feat.index.month
    df_feat['day_of_year'] = df_feat.index.dayofyear
    df_feat['quarter'] = df_feat.index.quarter
    
    # Ensure is_weekend and is_holiday exist
    if 'is_weekend' not in df_feat.columns:
        df_feat['is_weekend'] = (df_feat['day_of_week'] >= 5).astype(int)
    if 'is_holiday' not in df_feat.columns:
        df_feat['is_holiday'] = 0  # Default to 0 if holiday logic not provided
        
    # Trigonometric Cyclical Encoding
    df_feat['hour_sin'] = np.sin(2 * np.pi * df_feat['hour'] / 24)
    df_feat['hour_cos'] = np.cos(2 * np.pi * df_feat['hour'] / 24)
    
    df_feat['month_sin'] = np.sin(2 * np.pi * df_feat['month'] / 12)
    df_feat['month_cos'] = np.cos(2 * np.pi * df_feat['month'] / 12)
    
    df_feat['day_of_week_sin'] = np.sin(2 * np.pi * df_feat['day_of_week'] / 7)
    df_feat['day_of_week_cos'] = np.cos(2 * np.pi * df_feat['day_of_week'] / 7)
    
    return df_feat

def create_lag_features(df, target_col, lags=[1, 2, 24, 168]):
    """
    Creates lag features for the specified target column.
    
    lags=[1, 2, 24, 168] correspond to t-1, t-2, t-24 (1 day ago), t-168 (1 week ago).
    """
    df_feat = df.copy()
    for lag in lags:
        df_feat[f'{target_col}_lag_{lag}'] = df_feat[target_col].shift(lag)
    return df_feat

def create_rolling_features(df, target_col, windows=[6, 24, 168]):
    """
    Creates rolling window statistics (mean, std, min, max) for the target column.
    
    Using shift(1) is CRITICAL here to prevent data leakage. If we calculate the rolling mean 
    of the current hour including the current hour's target, the model will have perfect 
    look-ahead information during training.
    """
    df_feat = df.copy()
    shifted_target = df_feat[target_col].shift(1)
    
    for window in windows:
        df_feat[f'{target_col}_roll_mean_{window}'] = shifted_target.rolling(window=window).mean()
        df_feat[f'{target_col}_roll_std_{window}'] = shifted_target.rolling(window=window).std()
        df_feat[f'{target_col}_roll_max_{window}'] = shifted_target.rolling(window=window).max()
        df_feat[f'{target_col}_roll_min_{window}'] = shifted_target.rolling(window=window).min()
        
    return df_feat

def create_weather_features(df, temp_col='temperature'):
    """
    Generates domain-specific thermodynamic features (HDD/CDD) and temperature interactions.
    """
    df_feat = df.copy()
    if temp_col in df_feat.columns:
        # Heating Degree Days (HDD) - energy needed to heat building (standard baseline 18°C)
        df_feat['HDD'] = np.maximum(0, 18.0 - df_feat[temp_col])
        # Cooling Degree Days (CDD) - energy needed to cool building (standard baseline 21°C)
        df_feat['CDD'] = np.maximum(0, df_feat[temp_col] - 21.0)
        
        # Temperature interactions
        if 'hour' in df_feat.columns:
            df_feat['temp_hour_interact'] = df_feat[temp_col] * df_feat['hour']
        else:
            df_feat['temp_hour_interact'] = df_feat[temp_col] * df_feat.index.hour
            
        # Temperature rolling stats to model thermal inertia (heat retention of buildings)
        df_feat['temp_roll_mean_6h'] = df_feat[temp_col].rolling(window=6, min_periods=1).mean()
        df_feat['temp_roll_mean_24h'] = df_feat[temp_col].rolling(window=24, min_periods=1).mean()
        
    return df_feat

def engineer_all_features(df, target_col, lag_list=[1, 2, 24, 168], roll_list=[6, 24, 168], temp_col='temperature'):
    """
    Master feature engineering pipeline combining all sub-components.
    
    Parameters:
    -----------
    df : pd.DataFrame
        Source dataframe.
    target_col : str
        Target column for lag and rolling features.
    lag_list : list
        Lags to generate.
    roll_list : list
        Rolling windows to generate.
    temp_col : str
        Temperature column name.
        
    Returns:
    --------
    pd.DataFrame: Cleaned dataframe with engineered features, dropping rows with NaN due to lags.
    """
    df_feat = create_temporal_features(df)
    df_feat = create_lag_features(df_feat, target_col, lag_list)
    df_feat = create_rolling_features(df_feat, target_col, roll_list)
    df_feat = create_weather_features(df_feat, temp_col)
    
    # Drop rows containing NaNs generated by rolling/lag shifts
    # We only drop rows that have NaNs in the specific engineered target lags to avoid 
    # dropping future forecasting rows that might contain NaNs in other unrelated columns 
    # (e.g. other sector consumptions or future targets during recursive projection).
    max_lag = max(lag_list) if len(lag_list) > 0 else 1
    df_feat.dropna(subset=[f'{target_col}_lag_{max_lag}'], inplace=True)
    
    return df_feat
